import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../DatabaseService.dart';

class LanguageProvider with ChangeNotifier {

  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;
  bool get isEnglish => _currentLanguage == 'en';

  bool get isRTL => _currentLanguage == 'ar';

  LanguageProvider() {
    _loadLanguage();
  }


  // Load saved language from device storage


  // Dictionary for all strings found in your files
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'start_btn':"Start",
      'next_btn':"Next",
      'skip':"skip",
      'signup_voice_instructions':"Sign up page. Please enter your full name and phone number to create an account.",
'signup_subtitle': "Create your account",
'full_name_label': "Full Name",
'full_name_hint': "Enter your name",
'signup_button': "Sign Up",
'already_have_account': "Already have an account? ",
'signin_link': "Sign In",
'error_invalid_signup_tts': "Please fill in your details correctly",
'error_enter_username': "Enter username",
'error_name_short': "Name must be at least 3 characters",
      'restaurants_title': 'Restaurants',
'filter_rating': 'Highest Rating',
'filter_distance': 'Nearest First',
'filter_reset': 'Reset Filters',
'restaurants_voice_hint': 'Say "Show me pizza places" or tap a restaurant',
'no_restaurants_found': 'No restaurants found.',
'error_loading': 'Error loading restaurants',
      'app_name': 'Rec-Order',
      'your_cart': 'Your Cart', // Added to match CartScreen
      'cart_empty': 'Your cart is empty', // Added
      'cart_voice_hint': 'Say "Remove pizza" or "Checkout"', // Added
      'home': 'Home',
      'orders': 'Orders',
      'profile': 'Profile',
      'cart': 'Your Cart',
      'checkout': 'Proceed to Checkout',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'delivery_fee': 'Delivery Fee',
      'track_order': 'Track Order',
      'reorder': 'Reorder',
      'favorites': 'Favorites',
      'history': 'Order History',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'phone_hint': 'Phone Number',
      'password_hint': 'Password',
      'logout': 'Logout',
      'personal_info': 'Personal Information',
      'address': 'Delivery Addresses',
      'payment': 'Payment Methods',
      'notifications': 'Notifications',
      'voice_settings': 'Voice Settings',
      'language': 'Language',
      'search_res': 'Search restaurants...',
     'order_history': 'Order History',
  'active_orders': 'Active Orders',
  'past_orders': 'Past Orders',
  'no_orders': 'No orders found',
  'items_label': 'items',
  'unknown_restaurant': 'Unknown Restaurant',
  'recently': 'Recently',
  
  'status_preparing': 'Preparing',
  'status_delivered': 'Delivered',
  'status_cancelled': 'Cancelled',
  'status_on_way': 'On the way',
    'no_addresses': 'No addresses saved yet.',
    'default_tag': 'DEFAULT',
    'edit': 'Edit',
    'delete': 'Delete',
    'add_new_address': 'Add New Address',
    'edit_address': 'Edit Address',
    'label': 'Label',
    'label_hint': 'e.g. Home, Work',
    'address_field': 'Address',
    'address_hint': 'Street, City, Province',
    'select_icon': 'Select Icon',
    'save_address': 'Save Address',
    'update_address': 'Update Address',
    'error_something_wrong': 'Something went wrong',
      'add_to_cart': 'Add to Cart',
      'cancel': 'Cancel',
  'home_label': 'Home',
  'work_label': 'Work',
  'other_label': 'Other',
  'error_fill_fields': 'Please fill in all fields',
  'address_updated': 'Address updated!',
  'address_saved': 'Address saved!',
  'favorites resturant': 'Favorite Restaurants',
  'login_to_see_favs': 'Please log in to see favorites',
  'no_favorites': 'No favorites yet',
  'start_hearting': 'Start hearting restaurants to see them here!',
  'explore_restaurants': 'Explore Restaurants',
  'error': 'Error',
  'nav_home': 'Home',
  'nav_orders': 'Orders',
  'nav_profile': 'Profile',
  'hello': 'Hello',
  'home_subtitle': 'What would you like to eat today?',
  'tap_to_speak': 'Tap to speak your order',
  'quick_actions': 'Quick Actions',
  'action_order': 'Order Food',
  'action_track': 'Track Order',
  'action_reorder': 'Reorder',
  'action_favorites': 'Favorites',
  'search_menu': 'Search menu items',
  'no_items_found': 'No items found',
  'voice_hint_menu': 'Say "Add Margherita pizza" or tap an item',
  'cat_all': 'All',
  'cat_pizza': 'Pizza',
  'cat_pasta': 'Pasta',
  'cat_salads': 'Salads',
  'cat_drinks': 'Drinks',
  'select_size': 'Select Size',
  'size_small': 'Small',
  'size_medium': 'Medium',
  'size_large': 'Large',
  'add_ons': 'Add-ons',
  'quantity': 'Quantity',
  'no_internet_title': 'Whoops!',
'no_internet_msg': 'Check your internet connection.',
'try_again': 'Try Again',
 'notifications_title': 'Notifications',
'voice_cmd_header': 'Voice Commands:',
'voice_cmd_examples': '"Turn on order updates", "Disable promotions", "Mute all notifications"',
'all_notifications': 'All Notifications',
'receiving_updates': 'Receiving updates',
'order_updates_sec': 'Order Updates',
'order_conf_title': 'Order Confirmation',
'order_conf_sub': 'When order is placed',
'order_prep_title': 'Order Preparing',
'order_prep_sub': 'Restaurant is preparing',
'out_delivery_title': 'Out for Delivery',
'out_delivery_sub': 'Driver is on the way',
'delivered_title': 'Order Delivered',
'delivered_sub': 'Order has arrived',
'promotions_sec': 'Promotions & Offers',
'new_rest_title': 'New Restaurants',
'new_rest_sub': 'New places near you',
'special_offers_title': 'Special Offers',
'special_offers_sub': 'Exclusive deals for you',
'discounts_title': 'Discounts & Coupons',
'discounts_sub': 'Save money on orders',
'ratings_sec': 'Ratings & Reviews',
'rate_order_title': 'Rate Your Order',
'rate_order_sub': 'Reminder to rate food',
'driver_ratings_title': 'Driver Ratings',
'driver_ratings_sub': 'Reminder to rate driver',
'methods_sec': 'Notification Methods',
'voice_ann_title': 'Voice Announcements',
'voice_ann_sub': 'Hear updates spoken aloud',
'sound_title': 'Sound',
'sound_sub': 'Play notification sounds',
'vibration_title': 'Vibration',
'vibration_sub': 'Phone vibrates on alerts',
'push_title': 'Push Notifications',
'push_sub': 'App notifications',
'sms_title': 'SMS Notifications',
'sms_sub': 'Text message updates',
'email_title': 'Email Notifications',
'email_sub': 'Updates via email',
'payment_title': 'Payment',
'payment_voice_hint': 'Say "Pay with card" or "Cash on delivery"',
'select_payment_method': 'Select Payment Method',
'credit_card': 'Credit / Debit Card',
'secure_payment': 'Secure payment',
'cash_on_delivery': 'Cash on Delivery',
'pay_on_receive': 'Pay when you receive',
'card_details': 'Card Details',
'card_number': 'Card Number',
'expiry_date': 'Expiry Date',
'cvv': 'CVV',
'confirmation': 'Confirmation',
'voice_pin_title': 'Voice PIN Confirmation',
'voice_pin_sub': 'Speak your 4-digit PIN',
'secure_note': 'Secure Payment\nYour payment information is encrypted and secure.',

'confirm_and_pay': 'Confirm & Pay',
'confirm_voice_first': 'Please confirm your Voice PIN first',
'personal_info_title': 'Personal Information',
'save_button': 'SAVE',
'full_name_label': 'Full Name',
'email_label': 'Email Address',
'phone_label': 'Phone Number',
'data_protection_note': 'Your data is encrypted and used only to improve your ordering experience.',
'profile_update_success': 'Profile Updated Successfully!',
'profile_update_fail': 'Failed to update',
'profile_title': 'Profile',
'user_name_placeholder': 'User Name',
'no_phone_placeholder': 'No phone added',
'profile_voice_hint': 'Say "Show order history"',
'recent_orders': 'Recent Orders',
'view_all': 'View All',
'no_recent_orders': 'No recent orders found.',
'restaurant_placeholder': 'Restaurant',

'reorder_button': 'Reorder',
'section_account': 'Account',
'section_preferences': 'Preferences',
'section_activity': 'My Activity',
'personal_info_tile': 'Personal Information',
'delivery_addresses_tile': 'Delivery Addresses',
'payment_methods_tile': 'Payment Methods',
'notifications_tile': 'Notifications',
'language_tile': 'Language',
'voice_settings_tile': 'Voice Settings',
'order_history_tile': 'Order History',
'favorites_tile': 'Favorite Restaurants',
'logout_button': 'Logout',
'signin_voice_instructions': "Sign in page. Please enter your phone number. If you don't have an account, say sign up.",
'welcome_title': "Welcome to Rec-Order",
'signin_subtitle': "Sign in to continue",
'phone_number_label': "Phone Number",
'stay_signed_in': "Stay signed in",
'signin_button': "Sign In",
'no_account_text': "Don't have an account? ",
'signup_link': "Sign Up",
'error_invalid_phone_tts': "Please enter a valid phone number",
'error_enter_phone': "Enter phone number",
'error_valid_phone_format': "Enter a valid number with country code (e.g., +966...)",
'error_invalid_phone_msg': "The provided phone number is not valid.",
'error_verification_failed': "Verification failed",
'track_order_title': 'Track Order',
'order_status_header': 'Order Status',
'order_details_header': 'Order Details',
'recorder_partner': 'RecOrder Partner',
'searching_driver': 'Searching for driver...',
'unit_minutes': 'min',
'unit_items': 'items',
'status_arrived': 'Arrived',
'step_confirmed_title': 'Order Confirmed',
'step_confirmed_sub': 'Restaurant has received your request',
'step_ready_title': 'Food Ready',
'step_ready_sub': 'Chef has finished preparing',
'step_way_title': 'On the Way',
'step_way_sub': 'Driver is heading to you',
'step_delivered_title': 'Delivered',
'step_delivered_sub': 'Enjoy your meal!',
'detail_order_id': 'Order ID',
'detail_restaurant': 'Restaurant',
'detail_items': 'Items',
'detail_total': 'Total',
'no_active_orders': 'No Active Orders',
'no_active_orders_sub': "You don't have any orders to track right now.",
'go_back_btn': 'Go Back',
'voice_prompt_track': 'Say "Where is my order?"',
'status_voice_prefix': 'Your order is currenty:',
'ob_title_1': 'Tap & Hold to Speak',
      'ob_sub_1': 'Press the mic button and speak your order clearly',
      'ob_title_2': 'Listen to Confirmations',
      'ob_sub_2': 'The app will read back your selections for verification',
      'ob_title_3': 'Say Commands Anytime',
      'ob_sub_3': 'Try: Order pizza, Show my cart, Track order',
      'voice_instruction_hint': 'Say "Next" or "Skip"',
      // Error & System Messages
      'session_expired': 'Error: Session expired.',
      'wrong_code': 'Incorrect code',
      'error_occurred': 'An error occurred.',
      'enter_6_digits': 'Please enter all 6 digits.',
      'account_not_found_voice': 'Account not found. Please create an account first.',
      // Voice Settings Page
      'voice_settings_title': 'Voice Settings',
      'voice_hint_text': 'Try: "Enable voice feedback", "Set speed to fast"',
      'voice_commands_main': 'Voice Commands',
      'voice_status_active': 'Active and listening',
      'voice_features_header': 'Voice Features',
      'voice_feedback_title': 'Voice Feedback',
      'voice_feedback_sub': 'Hear confirmations for actions',
      'wake_word_title': 'Wake Word Detection',
      'wake_word_sub': 'Say "Hey Say-Serve" to activate',
      'auto_listen_title': 'Auto-Listen',
      'auto_listen_sub': 'Always ready for commands',
      'voice_conf_title': 'Voice Confirmations',
      'voice_conf_sub': 'Confirm orders before placing',
      'speech_speed_header': 'Speech Speed',
      'voice_volume_header': 'Voice Volume',
      'voice_lang_header': 'Voice Language',
      'vol_silent': 'Silent',
      'vol_loud': 'Loud',

      'verify_title':"verfiy Phone Number",
      'verify_subtitle':"Enter the 6-digit code sent to ",
      'no_code':"Didn't receive the code?",
          'resend_btn':"Resend Code",
          'verify_btn':"Verfiy",
      'proceed_to_checkout':"Proceed to Checkout",
      'footer_almost_there':"your food is almost there!",
          'arrival_estimate_label':"Estimated Arrival",
          'rider_label':"1200+ deliveries",
          'address_error': "Please enter your address in your profile screen first",
          'address_label': "Delivery Address",
  'address_hint': "Enter your full address...",
  'address_update': "Update Address",
  'address_success': "Address Updated!",
  'address_error_checkout': "Please enter your address in your profile first",
    },
    'ar': {
      'address_label': "عنوان التوصيل",
  'address_hint': "أدخل عنوانك بالتفصيل...",
  'address_update': "تحديث العنوان",
  'address_success': "تم تحديث العنوان!",
  'address_error_checkout': "يرجى إدخال عنوانك في الملف الشخصي أولاً",
      'address_error': "يرجى إدخال عنوانك في شاشة الملف الشخصي أولاً",
      'footer_almost_there': "طعامك اقترب من الوصول!",
      'arrival_estimate_label': "الوقت المقدر للوصول",
      'rider_label': "أكثر من ١٢٠٠ عملية توصيل",
      'proceed_to_checkout': "المتابعة لإتمام الطلب",
      'verify_title': "تحقق من رقم الهاتف",
      'verify_subtitle': "أدخل الرمز المكون من 6 أرقام المرسل إلى ",
      'no_code': "لم تستلم الرمز؟",
      'resend_btn': "إعادة إرسال الرمز",
      'verify_btn': "تحقق",
      'start_btn':"أبداء",
      'next_btn':"اكمل",
      // Voice Settings Page
      'skip':'التخطى',
      'voice_settings_title': 'إعدادات الصوت',
      'voice_hint_text': 'جرب: "تفعيل الرد الصوتي"، "ضبط السرعة على سريع"',
      'voice_commands_main': 'الأوامر الصوتية',
      'voice_status_active': 'نشط ويستمع الآن',
      'voice_features_header': 'ميزات الصوت',
      'voice_feedback_title': 'الرد الصوتي',
      'voice_feedback_sub': 'سماع تأكيدات للإجراءات',
      'wake_word_title': 'التعرف على كلمة التنبيه',
      'wake_word_sub': 'قل "Hey Say-Serve" للتفعيل',
      'auto_listen_title': 'الاستماع التلقائي',
      'auto_listen_sub': 'الاستعداد الدائم للأوامر',
      'voice_conf_title': 'التأكيدات الصوتية',
      'voice_conf_sub': 'تأكيد الطلبات قبل إتمامها',
      'speech_speed_header': 'سرعة الكلام',
      'voice_volume_header': 'مستوى الصوت',
      'voice_lang_header': 'لغة الصوت',
      'vol_silent': 'صامت',
      'vol_loud': 'مرتفع',
      'ob_title_1': 'اضغط مطولاً للتحدث',
      'ob_sub_1': 'اضغط على الميكروفون وتحدث بطلبك بوضوح',
      'ob_title_2': 'استمع للتأكيدات',
      'ob_sub_2': 'سيقوم التطبيق بقراءة خياراتك للتأكد منها',
      'ob_title_3': 'قل أوامرك في أي وقت',
      'ob_sub_3': 'جرب: اطلب بيتزا، عرض السلة، تتبع الطلب',
      'voice_instruction_hint': 'قل "التالي" أو "تخطي"',
      // Error & System Messages
      'session_expired': 'خطأ: انتهت الجلسة.',
      'wrong_code': 'الرمز غير صحيح',
      'error_occurred': 'حدث خطأ ما.',
      'enter_6_digits': 'يرجى إدخال كافة الأرقام الستة.',
      'account_not_found_voice': 'الحساب غير موجود. يرجى إنشاء حساب أولاً.',
      'track_order_title': 'تتبع الطلب',
'order_status_header': 'حالة الطلب',
'order_details_header': 'تفاصيل الطلب',
'recorder_partner': 'شريك ريك-أوردر',
'searching_driver': 'جاري البحث عن سائق...',
'unit_minutes': 'دقيقة',
'unit_items': 'أصناف',
'status_arrived': 'وصل الطلب',
'step_confirmed_title': 'تم تأكيد الطلب',
'step_confirmed_sub': 'استلم المطعم طلبك بنجاح',
'step_ready_title': 'الطعام جاهز',
'step_ready_sub': 'انتهى الطاهي من تحضير وجبتك',
'step_way_title': 'في الطريق',
'step_way_sub': 'السائق في طريقه إليك الآن',
'step_delivered_title': 'تم التوصيل',
'step_delivered_sub': 'بالهناء والشفاء!',
'detail_order_id': 'رقم الطلب',
'detail_restaurant': 'المطعم',
'detail_items': 'الأصناف',
'detail_total': 'المجموع',
'no_active_orders': 'لا توجد طلبات نشطة',
'no_active_orders_sub': 'ليس لديك أي طلبات لمتابعتها حالياً.',
'go_back_btn': 'العودة',
'voice_prompt_track': 'قل "أين طلبي؟"',
'status_voice_prefix': 'حالة طلبك الآن هي:',
      'signup_voice_instructions': "صفحة إنشاء حساب. يرجى إدخال اسمك الكامل ورقم هاتفك لإنشاء حساب جديد.",
'signup_subtitle': "إنشاء حساب جديد",
'full_name_label': "الاسم الكامل",
'full_name_hint': "أدخل اسمك هنا",
'signup_button': "إنشاء حساب",
'already_have_account': "لديك حساب بالفعل؟ ",
'signin_link': "تسجيل الدخول",
'error_invalid_signup_tts': "يرجى تعبئة البيانات بشكل صحيح",
'error_enter_username': "الرجاء إدخال اسم المستخدم",
'error_name_short': "يجب أن يكون الاسم 3 أحرف على الأقل",
      'signin_voice_instructions': "صفحة تسجيل الدخول. يرجى إدخال رقم هاتفك. إذا لم يكن لديك حساب، قل إنشاء حساب.",
'welcome_title': "مرحباً بك في Rec-Order",
'signin_subtitle': "سجل دخولك للمتابعة",
'phone_number_label': "رقم الهاتف",
'stay_signed_in': "البقاء متصلاً",
'signin_button': "تسجيل الدخول",
'no_account_text': "ليس لديك حساب؟ ",
'signup_link': "إنشاء حساب",
'error_invalid_phone_tts': "يرجى إدخال رقم هاتف صحيح",
'error_enter_phone': "أدخل رقم الهاتف",
'error_valid_phone_format': "أدخل رقماً صحيحاً مع كود الدولة (مثال: +966...)",
'error_invalid_phone_msg': "رقم الهاتف المقدم غير صحيح.",
'error_verification_failed': "فشل التحقق من الرقم",
      'profile_title': 'الملف الشخصي',
'user_name_placeholder': 'اسم المستخدم',
'no_phone_placeholder': 'لم يتم إضافة رقم هاتف',
'profile_voice_hint': 'قل "عرض سجل الطلبات"',
'recent_orders': 'الطلبات الأخيرة',
'view_all': 'عرض الكل',
'no_recent_orders': 'لا توجد طلبات أخيرة.',
'restaurant_placeholder': 'مطعم',
'items_label': 'أصناف',
'status_delivered': 'تم التوصيل',
'reorder_button': 'إعادة طلب',
'section_account': 'الحساب',
'section_preferences': 'التفضيلات',
'section_activity': 'نشاطي',
'personal_info_tile': 'المعلومات الشخصية',
'delivery_addresses_tile': 'عنوان التوصيل',
'payment_methods_tile': 'طرق الدفع',
'notifications_tile': 'التنبيهات',
'language_tile': 'اللغة',
'voice_settings_tile': 'إعدادات الصوت',
'order_history_tile': 'سجل الطلبات',
'favorites_tile': 'المطاعم المفضلة',
'logout_button': 'تسجيل الخروج',
      'personal_info_title': 'المعلومات الشخصية',
'save_button': 'حفظ',
'full_name_label': 'الاسم الكامل',
'email_label': 'البريد الإلكتروني',
'phone_label': 'رقم الهاتف',
'data_protection_note': 'بياناتك مشفرة وتستخدم فقط لتحسين تجربة الطلب الخاصة بك.',
'profile_update_success': 'تم تحديث الملف الشخصي بنجاح!',
'profile_update_fail': 'فشل التحديث',
      'payment_title': 'الدفع',
'payment_voice_hint': 'قل "ادفع بالبطاقة" أو "الدفع عند الاستلام"',
'select_payment_method': 'اختر طريقة الدفع',
'credit_card': 'بطاقة ائتمان / مدى',
'secure_payment': 'دفع آمن',
'cash_on_delivery': 'الدفع عند الاستلام',
'pay_on_receive': 'ادفع عند استلام الطلب',
'card_details': 'تفاصيل البطاقة',
'card_number': 'رقم البطاقة',
'expiry_date': 'تاريخ الانتهاء',
'cvv': 'الرمز الثلاثي (CVV)',
'confirmation': 'التأكيد',
'voice_pin_title': 'تأكيد الرمز الصوتي',
'voice_pin_sub': 'انطق الرمز السري المكون من 4 أرقام',
'secure_note': 'دفع آمن\nمعلومات الدفع الخاصة بك مشفرة ومؤمنة تماماً.',
'subtotal': 'المجموع الفرعي',
'delivery_fee': 'رسوم التوصيل',
'tax': 'الضريبة',
'total': 'المجموع الكلي',
'confirm_and_pay': 'تأكيد ودفع',
'confirm_voice_first': 'يرجى تأكيد الرمز الصوتي أولاً',
'error': 'خطأ',
      'notifications_title': 'التنبيهات',
'voice_cmd_header': 'الأوامر الصوتية:',
'voice_cmd_examples': '"شغل تحديثات الطلب", "عطل العروض", "كتم جميع التنبيهات"',
'all_notifications': 'جميع التنبيهات',
'receiving_updates': 'استلام التحديثات',
'order_updates_sec': 'تحديثات الطلب',
'order_conf_title': 'تأكيد الطلب',
'order_conf_sub': 'عند إتمام الطلب',
'order_prep_title': 'تجهيز الطلب',
'order_prep_sub': 'المطعم يجهز طلبك',
'out_delivery_title': 'خرج للتوصيل',
'out_delivery_sub': 'السائق في الطريق إليك',
'delivered_title': 'تم التوصيل',
'delivered_sub': 'وصل الطلب بنجاح',
'promotions_sec': 'العروض والترويج',
'new_rest_title': 'مطاعم جديدة',
'new_rest_sub': 'أماكن جديدة بالقرب منك',
'special_offers_title': 'عروض خاصة',
'special_offers_sub': 'صفقات حصرية لك',
'discounts_title': 'الخصومات والكوبونات',
'discounts_sub': 'وفر المال على طلباتك',
'ratings_sec': 'التقييمات والمراجعات',
'rate_order_title': 'تقييم طلبك',
'rate_order_sub': 'تذكير بتقييم الطعام',
'driver_ratings_title': 'تقييم السائق',
'driver_ratings_sub': 'تذكير بتقييم السائق',
'methods_sec': 'طرق التنبيه',
'voice_ann_title': 'الإعلانات الصوتية',
'voice_ann_sub': 'سماع التحديثات بصوت عالٍ',
'sound_title': 'الصوت',
'sound_sub': 'تشغيل أصوات التنبيه',
'vibration_title': 'الاهتزاز',
'vibration_sub': 'اهتزاز الهاتف عند التنبيه',
'push_title': 'تنبيهات التطبيق',
'push_sub': 'إشعارات من خلال التطبيق',
'sms_title': 'الرسائل النصية',
'sms_sub': 'تحديثات عبر الرسائل النصية',
'email_title': 'البريد الإلكتروني',
'email_sub': 'تحديثات عبر البريد الإلكتروني',
      'no_internet_title': 'عذراً!',
'no_internet_msg': 'يرجى التحقق من اتصال الإنترنت.',
'try_again': 'إعادة المحاولة',
      'select_size': 'اختر الحجم',
  'size_small': 'صغير',
  'size_medium': 'وسط',
  'size_large': 'كبير',
  'add_ons': 'الإضافات',
  'quantity': 'الكمية',
  'add_to_cart': 'أضف للسلة',
      'search_menu': 'ابحث في القائمة',
  'no_items_found': 'لم يتم العثور على نتائج',
  'voice_hint_menu': 'قل "أضف بيتزا مارجريتا" أو اختر صنفاً',
  'cat_all': 'الكل',
  'cat_pizza': 'بيتزا',
  'cat_pasta': 'باستا',
  'cat_salads': 'سلطات',
  'cat_drinks': 'مشروبات',
      'nav_home': 'الرئيسية',
  'nav_orders': 'الطلبات',
  'nav_profile': 'الملف الشخصي',
  'hello': 'مرحباً',
  'home_subtitle': 'ماذا تحب أن تأكل اليوم؟',
  'tap_to_speak': 'اضغط للتحدث بطلبك',
  'quick_actions': 'إجراءات سريعة',
  'action_order': 'طلب طعام',
  'action_track': 'تتبع الطلب',
  'action_reorder': 'إعادة طلب',
  'action_favorites': 'المفضلة',
     'favorites resturant': 'المطاعم المفضلة',
  'login_to_see_favs': 'يرجى تسجيل الدخول لرؤية المفضلة',
  'no_favorites': 'لا يوجد مفضلات بعد',
  'start_hearting': 'ابدأ بإضافة المطاعم التي تحبها لرؤيتها هنا!',
  'explore_restaurants': 'استكشف المطاعم',
  'restaurants_title': 'المطاعم',
'filter_rating': 'الأعلى تقييماً',
'filter_distance': 'الأقرب أولاً',
'filter_reset': 'إعادة ضبط الفلاتر',
'restaurants_voice_hint': 'قل "أرني أماكن البيتزا" أو اضغط على مطعم',
'no_restaurants_found': 'لم يتم العثور على مطاعم.',
'error_loading': 'خطأ في تحميل المطاعم',
      'error_fill_fields': 'يرجى ملء جميع الحقول',
  'address_updated': 'تم تحديث العنوان!',
  'address_saved': 'تم حفظ العنوان!',
      'address': 'عناوين التوصيل',
    'no_addresses': 'لا يوجد عناوين محفوظة بعد',
    'default_tag': 'افتراضي',
    'edit': 'تعديل',
    'delete': 'حذف',
    'add_new_address': 'إضافة عنوان جديد',
    'edit_address': 'تعديل العنوان',
    'label': 'العنوان الوصفي',
    'label_hint': 'مثال: المنزل، العمل',
    'address_field': 'العنوان بالتفصيل',
    'address_hint': 'الشارع، المدينة، المحافظة',
    'select_icon': 'اختر أيقونة',
    'save_address': 'حفظ العنوان',
    'update_address': 'تحديث العنوان',
    'error_something_wrong': 'حدث خطأ ما',
      'app_name': 'ريك اوردر',
      'home': 'الرئيسية',
      'orders': 'طلباتي',
      'your_cart': 'سلتك',
      'cart_empty': 'سلتك فارغة',
      'cart_voice_hint': 'قل "احذف البيتزا" أو "إتمام الطلب"',
      'profile': 'حسابي',
      'cart': 'سلة التسوق',
      'checkout': 'إتمام الشراء',
     
      'track_order': 'تتبع الطلب',
      'reorder':  'ريك اوردر',
      'favorites': 'المفضلة',
      'history': 'سجل الطلبات',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'phone_hint': 'رقم الهاتف',
      'password_hint': 'كلمة المرور',
      'logout': 'تسجيل الخروج',
      'personal_info': 'المعلومات الشخصية',
     'cancel': 'إلغاء',
  'home_label': 'المنزل',
  'work_label': 'العمل',
  'other_label': 'أخرى',
      'payment': 'طرق الدفع',
      'notifications': 'التنبيهات',
      'voice_settings': 'إعدادات الصوت',
      'language': 'اللغة',
      'search_res': 'البحث عن مطاعم...',
      
      'order_history': 'سجل الطلبات',
  'active_orders': 'الطلبات النشطة',
  'past_orders': 'الطلبات السابقة',
  'no_orders': 'لا يوجد طلبات',

  'unknown_restaurant': 'مطعم غير معروف',
  'recently': 'مؤخراً',
 
  'status_preparing': 'جاري التحضير',

  'status_cancelled': 'ملغي',
  'status_on_way': 'في الطريق',
    }
  };




  void setLanguage(String langCode) {
    _currentLanguage = langCode;
    _updateFirestore(langCode);
    notifyListeners();
  }
// --- New: Load language from Firestore on App Start/Login ---
  Future<void> fetchRemoteLanguage() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final doc = await FirebaseFirestore.instance.collection('users').doc(user.uid).get();
      if (doc.exists && doc.data()?['language'] != null) {
        _currentLanguage = doc.data()!['language'];
        notifyListeners();
      }
    }
  }
Future<void> _updateFirestore(String lang) async {
  try {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      await FirebaseFirestore.instance.collection('users').doc(user.uid).set({
        'language': lang,
      }, SetOptions(merge: true)); // Use merge: true so you don't overwrite other user data
    }
  } catch (e) {
    debugPrint("Firestore Language Update Failed: $e");
  }
}

  String getText(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? key;
  }

  // --- LOADING LOGIC ---
  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('language_code') ?? 'en';
    notifyListeners();
  }

  // --- CHANGING LOGIC ---
  Future<void> changeLanguage(String langCode) async {
    if (_currentLanguage == langCode) return;
    _currentLanguage = langCode;

    // 1. Save locally
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', langCode);

    // 2. Save to Firestore (via DatabaseService)
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      await DatabaseService().updateUserLanguage( langCode);
    }

    notifyListeners();
  }

}